plugins {
    id 'com.android.library'
    id 'com.jakewharton.butterknife'
}

dependencies {
    implementation project(":platform:core")
    implementation project(':platform:lib')
    implementation project(":platform:base")
    implementation Libs.INSTANCE.ARouter
    annotationProcessor Libs.INSTANCE.ARouterAnnotation
    implementation Libs.INSTANCE.appCompat
    implementation Libs.INSTANCE.constraintLayout
    implementation Libs.INSTANCE.material
    implementation Libs.INSTANCE.rxjava
    implementation Libs.INSTANCE.rxAndroid
    implementation Libs.INSTANCE.butterknife
    annotationProcessor Libs.INSTANCE.butterknifeAnnotation
    implementation Libs.INSTANCE.autoDispose
    implementation Libs.INSTANCE.autoDisposeArchComponents
    implementation Libs.INSTANCE.autoDisposeLifecycle
    implementation Libs.INSTANCE.okio
    implementation Libs.INSTANCE.logger
    implementation Libs.INSTANCE.libaums
    implementation platform(Libs.INSTANCE.firebaseBOM)
    implementation Libs.INSTANCE.firebaseAnalytics
    implementation Libs.INSTANCE.firebaseCrashlytics
    implementation Libs.INSTANCE.segmentedButton
    implementation Libs.INSTANCE.retrofitGsonConverter
    implementation Libs.INSTANCE.localization
    implementation Libs.INSTANCE.lottie
    implementation Libs.INSTANCE.glide
}
