package fabscreen.platform.base.service.machine.controller;

public enum SACPPrintResponseErrorCode {
    PRINT_RESPONSE_SUCCESS(0),
    PRINT_RESPONSE_ERROR_LAST_GCODE_ON_PRINT(200 + 1),
    PRINT_RESPONSE_ERROR_PRINT_STATE_NOT_IDLE(200 + 2),
    PRINT_RESPONSE_ERROR_MACHINE_NOT_HOMED(200 + 3),
    PRINT_RESPONSE_ERROR_GCODE_FILE_NOT_AVAILABLE(200 + 4),
    PRINT_RESPONSE_ERROR_PRINT_STATE_NOT_PRINTING(200 + 5),
    PRINT_RESPONSE_ERROR_PRINT_STATE_NOT_IN_PAUSED(200 + 6),

    // not available for now
    PRINT_RESPONSE_ERROR_POWER_LOSS_DATA_NOT_AVAILABLE(200 + 7),
    PRINT_RESPONSE_ERROR_POWER_LOSS_DETECTION_FAILED(200 + 8),
    PRINT_RESPONSE_ERROR_GCODE_FILE_NOT_PUSHED(200 + 9),

    PRINT_RESPONSE_ERROR_ENV_SAVE_FAILED_WHILE_PAUSING(200 + 10),
    PRINT_RESPONSE_ERROR_ENV_READ_FAILED_WHILE_RESUMING(200 + 11),
    PRINT_RESPONSE_ERROR_STOP_PARA_UNDEFINED(200 + 12),
    PRINT_RESPONSE_ERROR_ENV_READ_FAILED_WHILE_RECOVERING(200 + 13),
    PRINT_RESPONSE_ERROR_TOOL_HEAD_NOT_MATCHED(200 + 14),
    PRINT_RESPONSE_ERROR_STAND_BY_FAILED_WHILE_RECOVERING(200 + 15),
    PRINT_RESPONSE_ERROR_TOOL_HEAD_NOT_FOUND(200 + 16),
    PRINT_RESPONSE_ERROR_TOOL_HEAD_OFFLINE(200 + 17),
    PRINT_RESPONSE_ERROR_REQUEST_PROHIBITED_WITH_EXCEPTION(200 + 18),
    PRINT_RESPONSE_ERROR_EXTRUDER_STATUS_ERROR(200 + 19),
    PRINT_RESPONSE_ERROR_EXTRUDER_TYPE_ERROR(200 + 20),
    PRINT_RESPONSE_ERROR_EXTRUDER_TEMP_ERROR(200 + 21),
    PRINT_RESPONSE_ERROR_FILAMENT_NOT_FILLED(200 + 22),
    PRINT_RESPONSE_ERROR_CNC_MOTOR_OVER_CURRENT(200 + 23),
    PRINT_RESPONSE_ERROR_CNC_PCB_TEMP_ERROR(200 + 24),
    PRINT_RESPONSE_ERROR_CNC_MOTOR_TEMP_ERROR(200 + 25),
    PRINT_RESPONSE_ERROR_CNC_VOLT_ERROR(200 + 26),
    PRINT_RESPONSE_ERROR_ENCLOSURE_PANEL_OPEN(200 + 27),
    PRINT_RESPONSE_ERROR_LASER_IMU_CONNECTION_ERROR(200 + 28),
    PRINT_RESPONSE_ERROR_LASER_TUBE_TEMP_OVERHEATED(200 + 29),
    PRINT_RESPONSE_ERROR_LASER_TUBE_SLANTING(200 + 30),
    PRINT_RESPONSE_ERROR_LASER_PWN_ERROR(200 + 31),
    PRINT_RESPONSE_ERROR_TUBE_TEMP_RESISTOR_SHORTED(200 + 32),
    PRINT_RESPONSE_ERROR_LASER_PCB_TEMP_OVERHEATED(200 + 33),
    PRINT_RESPONSE_ERROR_LASER_FAN_ERROR(200 + 34),
    PRINT_RESPONSE_ERROR_ENCLOSURE_NOT_DETECTED_IN_LASER_MODE(200 + 35);

    private int value = 0;

    SACPPrintResponseErrorCode(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }

    public boolean valueEquals(int retCode) {
        return this.value == retCode;
    }

}
